
[package]

name = "ark-cli"
version = "0.1.0"
authors = ["Ark Ecosystem <info@ark.io>"]
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
log = "0.4"
env_logger = "0.9"
ark-lib = "0.0.0-alpha01"